### ISSUE TITLE
Set the npm registry?

### ISSUE THREAD

**Issue by erdog** [srs/gradle-node-plugin#105]
Hi,

Is it possible to set a custom registry URL for NPM? If not, can this feature be implemented?

Thanks!

**Comment by idooo** [comment]
Try to create .npmrc file in a project folder with your registry (and other settings) like:

```
registry = http://domain-example.com/nexus/content/groups/npm/
```

**Comment by erdog** [comment]
Thanks that worked!

**Comment by jakemonO** [comment]
where do I put the .npmrc file in my project for the gradle plugin's npm to access?
