### ISSUE TITLE
Bower fails when node is not globally installed

### ISSUE THREAD

**Issue by IsNull** [srs/gradle-node-plugin#106]
I have a Gradle sub-module which is a web application which has to be built as part of the java backend.
The below Gradle build script works well on systems which have node properly installed, but bower will fail on systems which don't have node in the $PATH:

**gradle.build**
```
plugins {
    id "com.moowork.node" version "0.12"
}

task build(type: Exec, dependsOn: ['bower']){
    workingDir "${projectDir}"
    commandLine "gulp", "build-prod"
}

node {
    download = true
}

// Install npm and the bower components for front-end library management
task bower(dependsOn: 'npmInstall', type: Exec){
    println "Installing bower dependencies..."
    commandLine './node_modules/bower/bin/bower', 'install'
}
```

The bower Task's commandLine `commandLine './node_modules/bower/bin/bower', 'install'` failes with

>bower/usr/bin/env: node: No such file or directory
 FAILED

>FAILURE: Build failed with an exception.

>* What went wrong:
Execution failed for task ':warden-webapp:bower'.
Process 'command './node_modules/bower/bin/bower'' finished with non-zero exit value 127

Bower cant find `.gradle/nodejs/node-v4.4.0-darwin-x64/bin/node`.

The build script works on my local machine and it works on Travis. But it fails on JitPack which does not have node around by default.

As a workaround I probably could symlink the `.gradle/nodejs/node-v4.4.0-darwin-x64/bin/node` to /usr/bin or something like that.

Is there a better way to handle this?

**Comment by raulgd** [comment]
Install Bower through an NPM task instead, using something like this:

```groovy
apply plugin: 'com.moowork.node'

node {
	version = '6.2.0'
	npmVersion = '3.9.0'
	distBaseUrl = 'https://nodejs.org/dist'
	download = true
	workDir = file("${project.projectDir}/nodejs")
	nodeModulesDir = file("${project.projectDir}/node_modules")
	if (!nodeModulesDir.isDirectory()) {
		nodeModulesDir.mkdirs()
	}
}

task npmCacheConfig(type: NpmTask, dependsOn: nodeSetup) {
	description = "Configure the NPM cache"
	def npmCacheDir = "${project.projectDir}/npm-cache"
	outputs.files file(npmCacheDir)
	args = ['config', 'set', 'cache', npmCacheDir]
}

task npmInstallBower(type: NpmTask, dependsOn: npmCacheConfig) {
	description = "Install Bower"
	args = ['install', 'bower']
}
```

That worked for me, hope that helps

**Comment by IsNull** [comment]
Thanks for your response. How do you invoke bower after you installed it via this npm task? The same way I do it?

```groovy
task bower(dependsOn: ['npmInstall', 'npmInstallBower'], type: Exec){
    println "Installing bower dependencies..."
    commandLine './node_modules/bower/bin/bower', 'install'
}
```

Because after your 

```groovy
task npmInstallBower(type: NpmTask, dependsOn: npmCacheConfig) {
    description = "Install Bower"
    args = ['install', 'bower']
}
```
_bower_ is not in the path

**Comment by raulgd** [comment]
If you check the node closure configuration on my first post, I setted a nodeModulesDir property, which is the path of the node_modules folder, so that's where bower lives, in this case it's ${project.projectDir}/node_modules

You really should stop relying on commandLine and first try to read the documentation and use the plugins, as that's what it's designed to do, using commandLine should be your last resort, it seems as a hack, just a wrapper to an external script, as Gradle is a build automation tool, it's designed to replace external build scripts as much as possible.

Running Bower is a NodeJS task, and as any NodeTask it should work with something like this:

```groovy
task appBowerInstall(type: NodeTask, dependsOn: npmInstallBower) {
	description = "Installs dependencies using Bower"
	script = file("${project.projectDir}/node_modules/bower/bin/bower")
	workingDir = file("${project.projectDir}/src/main/web")
	args = ['install']
}
```
Where workingDir is the folder where you want to execute the bower install command on.

I hope that helps.

**Comment by IsNull** [comment]
Thanks for your explanation, I'll try to avoid using the command line in future.

>it seems as a hack
Absolutely, this is why I'm here asking about it :)

> as Gradle is a build automation tool, it's designed to replace external build scripts as much as possible.

Yes, but sadly the reality is: I have 3 dependency management tools in a single Java Web project: maven, npm and bower, and two build systems: Gradle and Gulp. At least my build does no longer require any pre installed tools, because all these things are automatically installed now if Gradle build is invoked.

But in the long term, I have to get rid of at least bower and only use npm.
