### ISSUE TITLE
Expose node task's execResult

### ISSUE THREAD

**Issue by ljohnston** [srs/gradle-node-plugin#11]
The node task should expose it's execResult as the Gradle Exec task does.

Use case:  I want to ignore the exit value of some of my node-based test tasks (i.e. ignoreExitValue = true), but retrieve their actual success/failure status via execResult.exitValue.

Thanks,
Lance

**Comment by nkoterba** [comment]
@johnrengelman Can you share how you were able to redirect output/error streams?

I'm trying to do the same thing, but `standardOutput` and `errorOutput` are not exposed on the Node/Npm Tasks (which wrap and insulate an internal Exec runner) so not sure how to do this.  My thought was:

```groovy
standardOutput = new ByteArrayOutputStream()
    errorOutput = standardOutput
    ignoreExitValue = true
    doLast {
        if (result.exitValue != 0) {
            println(standardOutput.toString())
            throw new GradleException("exec failed; see output above")
        }
    }
```

But `standardOutput` as I mentioned isn't defined on NodeTask or NpmTask.

**Comment by nkoterba** [comment]
I was able to get something to work, although I'm not sure it's the best strategy.  If either of you have better suggestion, would appreciate it.

```groovy
ignoreExitValue = true
    def execRunner = null
    execOverrides {
        execRunner = it
        it.standardOutput = new ByteArrayOutputStream()
        it.errorOutput = it.standardOutput
    }
    doLast {
        if (result.exitValue != 0) {
            println(execRunner.standardOutput.toString())
            throw new GradleException("exec failed; see output above")
        }
    }
```
