### ISSUE TITLE
how do set npm install work dir

### ISSUE THREAD

**Issue by yidongnan** [srs/gradle-node-plugin#112]
my package.json in ${project.projectDir}/src/main/resources path

> node {
    version = '5.10.0'
    npmVersion = '3.8.3'
    distBaseUrl = 'https://npm.taobao.org/dist'
    download = true
    nodeModulesDir = file("${project.projectDir}/src/main/resources")
}

exec ./gradlew npm_install

npm WARN enoent ENOENT: no such file or directory, open ***/package.json' 

how do set npm install work dir

**Comment by raulgd** [comment]
There is a property called workingDir, it would be something like this:

```groovy
task appNpmInstall(type: NpmTask, dependsOn: emberInstallCli) {
	description = "Installs dependencies from package.json"
	workingDir = file("${project.projectDir}/src/main/web")
	args = ['install']
}
```

Check a previous post where I showed how to install and run Bower in a specific folder, it should work the same way for you if you need to run other NodeJS or npm tasks.

https://github.com/srs/gradle-node-plugin/issues/106#issuecomment-220772548

**Comment by yidongnan** [comment]
@raulgd It work to me. Ths

**Comment by srs** [comment]
Closing this since it's resolved. Will improve the docs as a summer project :-)
