### ISSUE TITLE
Adding node {} block causes error "Gradle DSL method not found: node()"

### ISSUE THREAD

**Issue by stevies** [srs/gradle-node-plugin#113]
Using Ubuntu 16.04.  Intellij 2016.1.2

If I add node block - eg:

```
node {
  version = '4.2.6'
  npmVersion = '3.5.2'
  download = true
}
```

to my gradle build file, it causes error below.

> Error:(15, 0) Gradle DSL method not found: 'node()'
> Possible causes:<ul><li>The project 'xx' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
> <a href="fixGradleElements">Fix plugin version and sync project</a></li><li>The project 'xx' may be using a version of Gradle that does not contain the method.
> <a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
> <a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

Removing the node{} block - everything works OK, but then I have to have node installed.

Note - I am not using Android studio.  Why the reference to the Android Gradle plug-in?

**Comment by wenslayer** [comment]
Looks like you haven't declared the plugin. Try adding the following to the top of your `build.gradle`:
```groovy
buildscript {
    repositories {
        mavenCentral()
    }
}
plugins {
    id "com.moowork.node" version '0.12'
}
```

**Comment by stevies** [comment]
That seems to work OK.  Thanks.  

I had tried it like this - from the documentation: 
>
    buildscript {
        repositories {
            maven {
                url "https://plugins.gradle.org/m2/"
            }
        }
        dependencies {
            classpath "com.moowork.gradle:gradle-node-plugin:0.12"
        }
    }
    apply plugin: 'com.moowork.node'
>

Doing it that way gives error I described.

**Comment by srs** [comment]
Both methods in the documentation should work. Could you paste the whole `build.gradle` file that you have a problem with?

Thanks.
