### ISSUE TITLE
Error executing NodeTask type from a subproject: "Task with path 'nodeSetup' not found in project ':foo'"

### ISSUE THREAD

**Issue by wenslayer** [srs/gradle-node-plugin#115]
# Summary
Configuring the node plugin for a multi-project build, I can run a NodeTask task out of the rootProject, but I get an error as described in the subject when I try to run it out of a subproject.

Any suggestions on how to configure this properly? Any alternate approaches (other plugins?) to run the TypeScript compiler?

Please let me know if you need any further info, or would like me to try running different tests.

Thanks for your attention.
# Repro
#### settings.gradle
```groovy
include 'foo', 'bar'`
```
#### build.gradle
```groovy
buildscript { repositories { mavenCentral() } }
plugins { id "com.moowork.node" version '0.12' }
allprojects {
    node {
        download       = true    // download node
        workDir        = new File(rootProject.projectDir, '.gradle/nodejs')
        nodeModulesDir = workDir // colocate node modules with local node install
    }
    task installTypeScript(type: NpmTask) {
        workingDir = node.workDir
        args = ['install', 'typescript']
    }
    task runTypeScript(type: NodeTask, dependsOn: installTypeScript) {
        script = new File(node.nodeModulesDir, 'node_modules/typescript/bin/tsc')
        args = ['--version']
    }
}
```

## Gradle Version
```
$ gradle --version
------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------
Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c
Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.10.5 x86_64
```

# Expected Results
Running the task out of the rootProject works as expected:
```
$ rm -fr .gradle
$ gradle :runTypeScript
:nodeSetup
Download https://nodejs.org/dist/v4.4.0/node-v4.4.0-darwin-x64.tar.gz
:installTypeScript
typescript@1.8.10 node_modules/typescript
:runTypeScript
Version 1.8.10

BUILD SUCCESSFUL

Total time: 14.927 secs
```
**Note**: this places the node installation and node modules under the `.gradle/nodejs` directory under the root project:
```
$ ls -1 .gradle/nodejs/
node-v4.4.5-darwin-x64
node_modules

$ ls -1 .gradle/nodejs/node_modules/
typescript
```

# Actual Results
But running it from the subproject does not:
```
$ rm -fr .gradle
$ gradle :foo:runTypeScript

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':foo:runTypeScript'.
> Task with path 'nodeSetup' not found in project ':foo'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.309 secs
```

# Attempted Workarounds
## Manually add nodeSetup task for subprojects
I added the following blurb to `build.gradle`:
```groovy
subprojects {
    task nodeSetup(dependsOn: rootProject.nodeSetup) {}
}
```
A different error is now encountered:
```
$ rm -fr .gradle
$ gradle :foo:runTypeScript
:nodeSetup
Download https://nodejs.org/dist/v4.4.0/node-v4.4.0-darwin-x64.tar.gz
:foo:nodeSetup
:foo:installTypeScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foo:installTypeScript'.
> Extension of type 'NodeExtension' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.528 secs
```

**Comment by wenslayer** [comment]
Any thoughts, @srs? This is blocking me from adopting not only your plugin but others that extend it.

Am I declaring it correctly for use with a multi-project build? I'd appreciate any suggestions you can offer.

**Comment by srs** [comment]
Hi.

Thanks for the really detailed description. Will try out what you have done here and see if i can get it to work.

**Comment by srs** [comment]
Ok, it seems to be something wrong with the plugin when doing the multi-project build like you do. Will see what needs to be changed.

**Comment by srs** [comment]
Now I have something that works. If you use it like this instead, it will work:

```
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath "com.moowork.gradle:gradle-node-plugin:0.12"
  }
}

allprojects {
  apply plugin: 'com.moowork.node'

  ...
}

```

The only thing I do differently is to actually add the plugin on all projects and not just the root project. I do not know how to do this with the `plugins` closure.

**Comment by srs** [comment]
Seems that this is a limitation on gradle itself. See http://stackoverflow.com/questions/26236308/how-to-apply-plugin-to-allprojects-with-new-gradle-plugins-mechanism

So, you will have to stick with the "old" notation for now (the one above). Closing this issue.
