### ISSUE TITLE
download nodejs from a local folder ?

### ISSUE THREAD

**Issue by kbjp2** [srs/gradle-node-plugin#119]
Hi,
My company CI server doesn't have access to internet (even though proxy), and I would like to avoid installing a global nodejs instance on that box. Hence I tried to download the exe node package (I'm using windows) through: 
`distBaseUrl = "file:/${projectDir}/repo/nodejs"`
and have my node exe file installed under:
`${projectDir}/repo/nodejs/nodejs/v4.4.5/win-x64/node.exe`
That "almost" works in the sense that the exe file gets copied to the local .gradle folder, however after that I get:
`         > Could not get resource 'https://repo1.maven.org/maven2/org/nodejs/node/4.4.5/node-4.4.5.pom'.`
which seems quite strange as https://nodejs.org/dist/ doesn't have any pom file either.
Is there a way to make this local "download" to work ?
Thank you very much in advance for your feedback and your expertise.
Regards
kbjp2

**Comment by srs** [comment]
Hi.

Will check it out how this could be done. Which version of the plugin are you using?

**Comment by srs** [comment]
I verified it and it should work. The only thing is that when it does not find the node binary it will delegate to the next repo in chain. This is fixed for #120 . 

I verified with the following setup and it works as expected. You could try version 0.13 when it's out (within a couple of days) if you cannot get this to work. 

```
node {
  ...
  distBaseUrl = "file:/${projectDir}/repo/nodejs"
}
```

**Comment by srs** [comment]
It seems to work all right. Closing this. Reopen if still trouble.

**Comment by kbjp2** [comment]
version 0.13 works great for me ! :-)
That new version is really useful for people like me whose CI server doesn't have internet connectivity !
Thanks a lot for your expertise and your very prompt feedback.
Regards
