### ISSUE TITLE
How to pass env variable to npm install?

### ISSUE THREAD

**Issue by Jaygiri** [srs/gradle-node-plugin#128]
A quick question, how can I pass env variables to npmInstall task?

I would like to do:

NODEJS_ORG_MIRROR=https://mymirror.com/dist npm install

(Specifically this is for node-gyp)

**Comment by srs** [comment]
I never tried, but since `npmInstall` is a standard `NodeTask` it should be possible to do it like this:

```
npmInstall {
  environment = [
    'NODEJS_ORG_MIRROR': 'https://mymirror.com/dist'
  ]
}
```

**Comment by Jaygiri** [comment]
Thanks, it works! But to avoid rewriting full environment I am doing this:

`// Override dist url for node-gyp
npmInstall {
  def _env = [:]
  _env << System.getenv();
  _env["NODEJS_ORG_MIRROR"] = 'https://mynodejs.org/dist'
  environment _env
}`

**Comment by rkrisztian** [comment]
This would be simpler:

```groovy
npmInstall {
    environment = System.getenv() + ['NODEJS_ORG_MIRROR': 'https://mymirror.com/dist']
}
```

**Comment by cjones26** [comment]
I don't mean to resurrect a dead topic, but it seems like even though the above code:

> ```
>     void setEnvironment( final Map<String, ?> value )
>     {
>         this.runner.environment << value
>     }
> ```

Exists in the plugin version I'm utilizing, I was still forced to utilize:

`  environment = System.getenv() + ['NODEJS_ORG_MIRROR': 'https://mymirror.com/dist']`

Or else I was getting an error stating:

> > Task :npmBuild FAILED
> 'npm.cmd' is not recognized as an internal or external command,
> operable program or batch file

.Strange..
