### ISSUE TITLE
NPM run tasks with pre and/or post do not properly run

### ISSUE THREAD

**Issue by gkohen** [srs/gradle-node-plugin#146]
Hi,

As we started to use more NPM scripts with version 2.12, we've noticed some issues for this task:

```
task e2eTestWebApp(type: NpmTask) {
    outputs.upToDateWhen { false };
    args = ['run', 'e2e']
}
```

In package.json we have the following scripts:

```
    "e2e": "npm run protractor",
    "pree2e": "npm run webdriver:update -- --standalone"
```

When running npm run e2e from command line, it properly. That is it runs pree2e script and then the e2e one. 
When doing the same through the Gradle task above, it shows on the console the following commands:

```
npm run protractor
npm run webdriver:update -- --standalone
```

But the commands do not actually execute (no-op for both). I wonder if the blame is on the the way the gradle plugin runs NPM with npm_cli.js

Considering NPM scripts is becoming a prominent way of building web apps, it would be good if we can have some more tests/support to NPM run.

Thanks for a great plugin, by the way.

**Comment by bernyfox** [comment]
+1

**Comment by msc1776** [comment]
Also seeing this. Have you figured out a workaround?

**Comment by stevies** [comment]
It rather defeats some of the purpose of this plugin, but you can do something like:
```
task e2eTestWebApp(type: Exec) {
    workingDir = file("${project.projectDir}/whatever")
    executable = 'npm'
    args = ['run-script', 'e2e'']
}
```
Essentially, use the plugin to install node and run the npm install, then just run the usual npm scripts with npm as a normal executable.

**Comment by dartiga** [comment]
+1

**Comment by s0x** [comment]
I could not solve it by just using the above configuration. Though I spotted the reason of this issue described in #164
