### ISSUE TITLE
NPM run tasks with '&&' to execute multiple scripts do not run

### ISSUE THREAD

**Issue by msc117** [srs/gradle-node-plugin#149]
In build.gradle
```
task myTask(type: NpmTask) {
    args = ['run', 'myscript']
}
```
In package.json
```
"myscript": "npm run script1 && npm run script2",
"script1": "...",
"script2": "..."
```

In this example, when myTask is run, only script1 will be called. script2 is never called.

**Comment by msc1776** [comment]
Related to #146

**Comment by s0x** [comment]
This is actually related to #164

**Comment by mburri** [comment]
you don't need to define your own task in this case -
the node  plugin automatically creates a gradle task called npm_run_myscript.

you can run your npm script with:

`./gradlew npm_run_myscript`

and it works as expected.

you can also configure the task in your gradle script, e.g.

`
   npm_run_myscript {
       dependsOn npmInstall
   }
`

see this [gist](https://gist.github.com/mburri/bb3a447b60b1f58e2c8ac39d3b11c616) as an example...

**Comment by s0x** [comment]
Fair enough... no need for the task. And it works as long as you use the global node installation.
In case of downloading a local one It doesn't work on linux though. See #164 for more information
