### ISSUE TITLE
Do not add nodejs ivyRepo to project repositories

### ISSUE THREAD

**Issue by tkruse** [srs/gradle-node-plugin#16]
using both the node plugin and the version plugin causes our project to take an eternity to run gradle dependencyUpdates. See: https://github.com/ben-manes/gradle-versions-plugin/issues/30.
Not sure if nodejs needs to be added as an ivy repo to the project.

**Comment by ben-manes** [comment]
The npm repository could be added & removed on-demand. The versions plugin does this by gathering all the repositories across all subprojects, adding them to the project prior to execution, and removing the additions afterwards. This appears to work fine. If applied here it would reduce the scope to the npm repository to only when necessary, which I believe is the desired behavior.

**Comment by srs** [comment]
Oh, yes, that's a good solution. Will try to add/remove the npm repository on demand. Only needs that when setting up node anyway.

**Comment by jsnmoon** [comment]
Hi there, has there been any progress on this issue?

**Comment by srs** [comment]
I have not tried the add/remove repo on-demand solution yet. Will try to make a quick-fix in the following days. 

I am also experimenting with a solution that used JAR packaged node that's pushed to maven-central (and/or bintray). This way we can use the same maven-repository proxies without doing anything special. The only downside on this is the packaging and pushing of new node versions when it's released.

**Comment by srs** [comment]
I tested adding/removing repo on demand and it seems to work. Will try to add this in the comming days. I am in the process of reworking the node dependency resolution to make it more testable so will try to bake this into that.

**Comment by srs** [comment]
Hi, could you please check out latest code in master to see if it solves your problem?

**Comment by srs** [comment]
Fixed in 0.12-SNAPSHOT.
