### ISSUE TITLE
Broken npm symlink: Unable to call npm in scripts property

### ISSUE THREAD

**Issue by s0x** [srs/gradle-node-plugin#164]
Gradle's tartree does not keep symbolic links. Therefore the symbolic link to npm got lost. This leads to the inability to use npm in the scripts property.

See issue: https://issues.gradle.org/browse/GRADLE-2844

**Comment by s0x** [comment]
This only applies if a local copy is downloaded and used

### Steps to reproduce

1. Create package.json
```
{
  "name": "example",
  "version": "1.0.0",
  "scripts": {
    "myscript": "npm run script1 && npm run script2",
    "script1": "echo Script1",
    "script2": "echo Script2"
  }
}
```
2. Create build.gradle
```
...
apply plugin: "com.moowork.node"
node {
    download = true
}
task myTask(type: NpmTask) {
    args = ['run', 'myscript']
}
```

3. call `gradle myTask`

### Resulting Output
```
> npm run script1 && npm run script2

BUILD SUCCESSFUL
```
### Expected Output
```
> npm run script1 && npm run script2

> echo Script1
Script1

> echo Script2
Script2

BUILD SUCCESSFUL
```

**Comment by srs** [comment]
Hi.

I have tried what you describe here on existing code and it works as expected. What version of Gradle are you using?

**Comment by s0x** [comment]
I'm using Ubuntu 16.04LTS
```
Linux pc2307-linux 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
I tried it with Gradle 2.10 and 3.2.1. Exactly the same result. I'll give it a try on a Mac and come back to you with the results.

**Comment by s0x** [comment]
I just tried it on a Mac and It doesn't work there either. Have you set `download` to true? As described, this only occurs if you use a local node installation. Alternatively you could use the attached files to reproduce it

[project.zip](https://github.com/srs/gradle-node-plugin/files/630869/project.zip)

**Comment by s0x** [comment]
Digging a bit deeper into this it seems that this occures only in gradle-node-plugin >= 0.14 and was introduced by moving npm into the cache directory (00cc0c8).

**Comment by s0x** [comment]
@srs: Any update on this?

**Comment by sirianni** [comment]
We are hitting this issue as well.  Would be great if the pull request could be accepted.

**Comment by coreyog** [comment]
This became a real issue where I work when we updated from 0.11 to 1.0.1.

In dev we had node installed from 0.11 and since node was installed correctly things continued to work when we updated to 1.0.1 without a hitch. When we attempted to deploy to prod we did so from a different, clean environment which meant we were having 1.0.1 install node incorrectly. Gradle reported a successful build despite not actually building anything.

**Comment by coreyog** [comment]
I don't think the tar command is the way to go. It's not independent.

**Comment by s0x** [comment]
I know. I'd be happy to use a real platform independent solution here as well. I just can't see one. 
Well, the node installation is not platform independent anyhow. It takes windows into account separately while the can be assumed to be unix, I guess. Since I don't know any Unix system which does not come with a tar command, I don't consider this as a really big deal.
Actually I'd rather use this solution than other dirty hacks right now (e.g. having gradle tasks which install node globally and potentially overwrite other instances). If you have a real independent solution for this issue: Please let me know about it!

**Comment by DanielJRutledge** [comment]
What's the proper workaround for this? I imagine it would be to specify the cached npm directory manually in a given npm task using `workingDir`, but are there other options?
