### ISSUE TITLE
Gulp plugin 1.0.0 is not found in Gradle Central Plugin Repository

### ISSUE THREAD

**Issue by ahamana** [srs/gradle-node-plugin#170]
I specify the gradle-gulp-plugin 1.0.0 in the build.gradle.
```
plugins {
    id 'com.moowork.gulp' version '1.0.0'
}
```

But when running gulp tasks, I encounter the following error.
> Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> Gradle Central Plugin Repository (plugin 'com.moowork.gulp' has no version '1.0.0' - see https://plugins.gradle.org/plugin/com.moowork.gulp for available versions)

Colud you please push the version 1.0.0 to Gradle Central Plugin Repository?

Thank you in advance.

**Comment by srs** [comment]
Sorry. My mistake when I cut the 1.0.0 release. Did not add `grunt` and `gulp` meta data. Will do and report back on this thread when it's active.

**Comment by srs** [comment]
Added the metadata to bintray. Have to wait until `plugins.gradle.org` updates. 

* https://plugins.gradle.org/plugin/com.moowork.gulp
* https://plugins.gradle.org/plugin/com.moowork.grunt

**Comment by srs** [comment]
Use 1.0.1 instead and it should work. Closing this issue.

**Comment by ahamana** [comment]
@srs Many thanks for your quick action. I can download a new one.
