### ISSUE TITLE
Out of memory when used on Jenkins

### ISSUE THREAD

**Issue by dlabaj** [srs/gradle-node-plugin#180]
We are running into an issue where this gradle node plugin is running out of memory only when run through Jenkins.  We receive the following error below:

**09:08:24 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory**
09:08:25 
09:08:25 npm ERR! Windows_NT 6.1.7601
09:08:25 npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
09:08:25 npm ERR! node v4.4.3
09:08:25 npm ERR! npm  v2.15.1
09:08:25 npm ERR! code ELIFECYCLE
09:08:25 npm ERR! Exit status 3
09:08:25 npm ERR! 
09:08:25 :projects:my-project-html:build FAILED
09:08:25 :buildDashboard UP-TO-DATE
09:08:45 
09:08:45 FAILURE: Build failed with an exception.
09:08:45 
09:08:45 * What went wrong:
09:08:45 Execution failed for task ':projects:my-project-html:build'.
09:08:45 > Process 'command 'npm.cmd'' finished with non-zero exit value 1
09:08:45 
09:08:45 * Try:
09:08:45 Run with --info or --debug option to get more log output.
09:08:45 
09:08:45 * Exception is:
09:08:45 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projects:my-project-html:build'.
09:08:45 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
09:08:45 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
09:08:45 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
09:08:45 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
09:08:45 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
09:08:45 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
09:08:45 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
09:08:45 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
09:08:45 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
09:08:45 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
09:08:45 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
09:08:45 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
09:08:45 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
09:08:45 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
09:08:45 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
09:08:45 Caused by: org.gradle.process.internal.ExecException: Process 'command 'npm.cmd'' finished with non-zero exit value 1
09:08:45 	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
09:08:45 	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
09:08:45 	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:165)
09:08:45 	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:814)
09:08:45 	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:810)
09:08:45 	at org.gradle.api.Project$exec$4.call(Unknown Source)
09:08:45 	at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.groovy:36)
09:08:45 	at com.moowork.gradle.node.npm.NpmExecRunner.doExecute(NpmExecRunner.groovy:26)
09:08:45 	at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:66)
09:08:45 	at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
09:08:45 	at com.moowork.gradle.node.npm.NpmTask.exec(NpmTask.groovy:90)
09:08:45 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
09:08:45 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
09:08:45 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
09:08:45 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
09:08:45 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
09:08:45 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
09:08:45 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
09:08:45 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
09:08:45 	... 14 more
09:08:45 
09:08:45 
**09:08:45 BUILD FAILED**

Any thoughts or work around would be helpful.  We are only seeing this through Jenkins, and if we attempt to run it on the build machine without using Jenkins we don't receive this out of memory issue.  Thanks.

**Comment by srs** [comment]
What do your in Gradle looks like? You could try to increase memory for node by adding it as an argument to the gradle task.

```
args = ['--max-old-space-size=4096']
```

`--max-old-space-size=4096` is setting the memory limit for node to 4GB.

**Comment by srs** [comment]
Sorry, it seems that it's impossible to set that now. Have a PR that fixes this. See #141.

**Comment by dlabaj** [comment]
@srs Yeah saw the PR after posting this.  Seems like that's what we need in order to increase the memory.

**Comment by dlabaj** [comment]
@srs We tried it with the update from the PR above and it resolved our issue.  Thanks.  Any estimate on when this will make it into the release?

**Comment by dlabaj** [comment]
Closing issue since it's a duplicate of the one above and a fix is on the way.
