### ISSUE TITLE
Gulp plugin 1.1.0 is not found in Gradle Central Plugin Repository

### ISSUE THREAD

**Issue by ahamana** [srs/gradle-node-plugin#188]
I specify the gradle-gulp-plugin 1.0.0 in the build.gradle.

```
plugins {
    id 'com.moowork.gulp' version '1.1.0'
}
```

But when running gulp tasks, I encounter the following error.
> Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> Gradle Central Plugin Repository (plugin 'com.moowork.gulp' has no version '1.1.0' - see https://plugins.gradle.org/plugin/com.moowork.gulp for available versions)

Colud you please push the version 1.1.0 to Gradle Central Plugin Repository?

Thank you in advance.

**Comment by srs** [comment]
Ah, right. I see that something went wrong with the publishing. Will fix it right away.

**Comment by srs** [comment]
Now it should work. Just update to use `1.1.1`.
