### ISSUE TITLE
Plugins not available on gradle plugins directory

### ISSUE THREAD

**Issue by rabbitfr** [srs/gradle-node-plugin#193]
Hi, 

While applying the plugin works perfectly, I can't get it to 
work as a dependency : 

dependencies {
    compile "com.moowork.gradle:gradle-node-plugin:1.1.1"
    compile "com.moowork.gradle:gradle-gulp-plugin:1.1.1"
}

The url https://plugins.gradle.org/m2/com/moowork/gradle/gradle-gulp-plugin/1.1.1/gradle-gulp-plugin-1.1.1.jar redirects to a 404 https://repo.jfrog.org/artifactory/libs-release-bintray/com/moowork/gradle/gradle-grunt-plugin/ 

Any clue ?

Thanks for your great work !

**Comment by srs** [comment]
Yes, from 1.0 both grunt and gulp is included in the node plugin. If you use the dependency-way, then please refer to this https://github.com/srs/gradle-node-plugin/blob/master/docs/installing.md

So, basically you just remove the "gulp" dependency and is left with:

```
dependencies {
  compile "com.moowork.gradle:gradle-node-plugin:1.1.1"
}
```

And thanks for the kind words. Just let me know if it's working.

**Comment by rabbitfr** [comment]
Thanks, 

It works now !

**Comment by srs** [comment]
Nice. Closing this.
