### ISSUE TITLE
Support execOverrides on NpmSetupTask

### ISSUE THREAD

**Issue by nkoterba** [srs/gradle-node-plugin#196]
We have recently upgraded from the old mooworks `gulp` and `node` plugins to the latest single "repo" version.

In our old setup, we liked to squelch NPM, Node, and Gulp tasks unless they failed with the following:

```groovy
hideNonFailingOutput = {
        ignoreExitValue = true
        def execRunner = null
        execOverrides {
            execRunner = it
            it.standardOutput = new ByteArrayOutputStream()
            it.errorOutput = it.standardOutput
        }
        doLast {
            if (result.exitValue != 0) {
                println(execRunner.standardOutput.toString())
                throw new GradleException("exec failed; see output above")
            }
        }
    }
```

_build.gradle_
```groovy
npmSetup {
       configure hideNonFailingOutput
    }
```

In the newest version, when I try to run `gradle npmSetup`, the following error occurs:
```
> Could not find method execOverrides() for arguments [build_13tmtfk6heqf6fa4c13hvdop7$_run_closure3$_closure30$_closure39@1c0d19ca] on task ':webclient:npmSetup' of type com.moowork.gradle.node.npm.NpmSetupTask.
```

When I look at the current source I see that `NpmSetupTask` uses an internal `NpmExecRunner` (https://github.com/srs/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/npm/NpmSetupTask.groovy#L83), but does not provide a way to configure that ExecRunner other than passing `args`.

Was this functionality or capability removed for a reason?  If not, would it be possible to add back in a way to configure `execOverrides` on an `NpmSetupTask` (so these could be passed internally to the NpmExecRunner or configured)?

**Comment by srs** [comment]
That was not an intentional removal. Will add that back in. Marking this as a bug.

**Comment by srs** [comment]
Could you provide a complete example of this?

**Comment by nkoterba** [comment]
@srs I'm confused what you mean by complete example?

My original post shows how we are trying to provide `execOverrides` for the **npmSetup** task.  However, **npmSetup** no longer exposes or supports execOverrides configuration.  We are doing this so we can squelch NPM output which we don't need in our gradle output unless an error occurs.

Something as simple as:
```groovy
npmSetup {
   execOverrides {

   } 
}
```

should cause the error since execOverrides is not defined anymore on the NpmSetupTask.  

Error output:
```
* What went wrong:
A problem occurred evaluating project ':webclient'.
> Could not find method execOverrides() for arguments [build_89gbdgndlf88e5p5k8082bhzi$_run_closure3$_closure28$_closure37@11336498] on task ':webclient:npmSetup' of type com.moowork.gradle.node.npm.NpmSetupTask.

```

**Comment by srs** [comment]
Oh, sorry. Misunderstood the original issue. Will create a simple example of this and then fix it for `NpmSetupTask` and all the other tasks.
