### ISSUE TITLE
npmInstall: set debug level?

### ISSUE THREAD

**Issue by cpolzer** [srs/gradle-node-plugin#200]
Hi!

For debugging proxy settings and local hosted npm registries I am not able to figure out how to set  the --loglevel option... how would i do this?

**Comment by TheLarkInn** [comment]
Have you attempted `npm set loglevel silly`? Otherwise, I've been looking for this same information but haven't found many answers.

**Comment by srs** [comment]
Added this to the FAQ (https://github.com/srs/gradle-node-plugin/blob/master/docs/faq.md). Thanks for helping out. 

Closing this issue.
