### ISSUE TITLE
Yarn commands not working

### ISSUE THREAD

**Issue by frangarcia** [srs/gradle-node-plugin#207]
Not sure If I understood the way node plugin works for yarn commands but I am having problems when running yarn commands if yarn is not installed in the system. 

I am trying to use the gradle-node-plugin to run some yarn commands without installing yarn locally like

```
gradle yarn_test
```

but it throws the exception

Caused by: java.io.IOException: Cannot run program "yarn" (in directory "/my-folder"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 4 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 5 more

This is the build.gradle content

```
plugins {
	id "com.moowork.node" version "1.1.1"
}
```

This problem goes away as soon as I install yarn locally so I don't know if I am missunderstanding something but I thought the idea of this plugin was basically avoid the need of having to install yarn locally.

**Comment by srs** [comment]
It should work without installing yarn globally. I tried it again here on my Mac. Uninstalled global yarn and ran the example https://github.com/srs/gradle-node-plugin/tree/master/examples/simple-yarn. 

Could you try to run the same example?

Also, which OS are you running on?

**Comment by frangarcia** [comment]
Thanks for the quick answer. I think what the problem is, I didn't add the download = true option. With that option, everything works fine.

**Comment by srs** [comment]
Great. Closing this.

**Comment by swellingt0n** [comment]
I am having the same issue on OSX with yarn installed globally via homebrew. It's trying to execute yarn from the default `yarnWorkDir` but the `yarnSetupTask` never downloads yarn even though download is set to true.

Gradle config:
```
node {  
  version = '5.1.0'  
  yarnVersion = '0.23.2'  
  download = true  
  nodeModulesDir = 'some/dir'  
  distBaseUrl = 'some/remote/dir'  
}
```
