### ISSUE TITLE
NoClassDefFoundError: ShortTypeHandling

### ISSUE THREAD

**Issue by tkruse** [srs/gradle-node-plugin#21]
Version 0.6 of the plugin throws that exception when run with gradle 1.x.
See:
http://glaforge.appspot.com/article/groovy-2-3-5-out-with-upward-compatibility?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+glaforge+%28Guillaume+Laforge%27s+blog+feed%29

If nothing else, the documentation could mention the additional dependency required.

However I believe it is also possible to build and release the jar with gradle 1.12, then the plugin should still work fine with both gradle1 and gradle2, and your users will not be affected.

**Comment by jaylinski** [comment]
+1

**Comment by dzapata** [comment]
+1 on this; I just hit this issue and luckily I found this issue with the fix.

**Comment by srs** [comment]
Sorry, but I had no focus retaining Gradle 1.x compatibility. Do you think many people are stuck on Gradle 1.x?

**Comment by justadropofwater** [comment]
I am :( Looks like this plugin isn't the solution I was looking for. I'll do a little bit of digging to see how much of a pain this is port down.

**Comment by justadropofwater** [comment]
Aha! (Look's like there is a quick-fx.)[http://glaforge.appspot.com/article/groovy-2-3-5-out-with-upward-compatibility]

**Comment by srs** [comment]
Did this quick fix work for you?

**Comment by justadropofwater** [comment]
Sure did, craziness.

**Comment by srs** [comment]
Closing this.
