### ISSUE TITLE
NPM/Yarn is downloaded from the default registry if npmVersion or yarnVersion is set

### ISSUE THREAD

**Issue by rkrisztian** [srs/gradle-node-plugin#226]
If you have this in your Gradle script:

```
node {
    npmVersion = '5.0.1'
    download = true
}
```

Or this:

```
node {
    yarnVersion = '0.23.4'
    download = true
}
```

Then NPM/Yarn will be downloaded from `registry.npmjs.org`, rather than from the mirror site I set in `<PROJECT_DIR>/.npmrc`.

The reason is, when installing a global package (`npm install -g --prefix=<PROJECT_DIR>/.gradle/npm/... npm@<VERSION>`), the registry setting in `<PROJECT_DIR>/.npmrc` is not used.

So far I know the followings:

* What works:
** Set `registry=http://my-registry.com:1234/repository/` in `~/.npmrc`. (A project-level setting would be more ideal for my company though.)
* What does not work:
** ```npmSetup.args += ['--registry=http://my-registry.com:1234/repository/']
yarnSetup.args += ['--registry=http://my-registry.com:1234/repository/']``` (In those tasks, `args` is write-only, according to Gradle.

**Comment by srs** [comment]
Ah, right. The args should be modified to allow to be added too. Will mark this as a bug.

**Comment by mconner** [comment]
How is this supposed to be used?  (Not a Gradle expert, so bear with me).  The plugin apply()  does:
```
        this.project.afterEvaluate {
            this.config.variant = new VariantBuilder( this.config ).build()
            configureSetupTask()
            configureNpmSetupTask()
            configureYarnSetupTask()
        }
```
and configureNpmSetupTask calls npmSetupTask.configureVersion, which set the args:

```
    void configureVersion( String npmVersion )
    {
        if ( !npmVersion.isEmpty() )
        {
            logger.debug( "Setting npmVersion to ${npmVersion}" )
            setArgs( ['install', '--global', '--no-save', '--prefix', getVariant().npmDir, "npm@${npmVersion}"] )
            enabled = true
        }
    }

```
This  apparently overwrites them if I try do do `npmSetup.arg += ...`, as indicated by @rkrisztian:
It does seem to work if I do this in an afterEvaluate, but that seems an odd way to define that, and I'm not sure if its guaranteed who comes first, project or plugin.

**Comment by rkrisztian** [comment]
I use it like this:

```
afterEvaluate() {
    npmSetup.args += ['--registry=https://some.url/here/']
}
```

But I agree that the plugin shouldn't be using {{afterEvaluate}} to initialize the arguments, as that is a bad design that also forces us have to use {{afterEvaluate}} as well.
