### ISSUE TITLE
When using Buildship to run Gradle, error > A problem occurred starting process 'command 'npm''

### ISSUE THREAD

**Issue by mikecargal** [srs/gradle-node-plugin#255]
Buildship doesn't give much of a way to see what's going on, but the plugin works fine when running gradle  from the command line.

I suspect that the plugin can't find node (or npm) when running within eclipse (build ship).

when starting a task in build ship, I get the following error:

------------------------------------------
Failure: Build failed with an exception
*What went wrong: 
Execution failed for task ":npmInstall'.
\> A problem occurred starting process 'command 'nom''

-------------------------------------------

Has anyone encountered this and have a suggestion for correcting the problem?

**Comment by MannyCalavera1** [comment]
`'command 'nom''` seems like a typo to me. Maybe you meant `npm`.
