### ISSUE TITLE
Is there a way to use the bundled npm?

### ISSUE THREAD

**Issue by mconner** [srs/gradle-node-plugin#272]
The docs say: 

> If npmVersion is specified, the plugin installs that version of npm into npmWorkDir by the npmSetup task and use it.
> If npmVersion is not specified and a locally-installed npm exists, The plugin will use it.
> Otherwise, the plugin will use the npm bundled with the version of node installation.

What I want is to use the npm bundled with the node version installed by the plugin, regardless of whether or not there's a locally (i.e. globally)  installed npm?   Is there a way to do that?

**Comment by yeikel** [comment]
I am also interested

**Comment by web-devel** [comment]
That's how the plugin works if you specify
```
{
  downlodad = true
}
```

**Comment by mconner** [comment]
So, I guess I am confused by the documentation.  We have:
>  **Configuring the Plugin**
// If true, it will download node using above parameters.
  // If false, it will try to use globally installed node.
  download = true

and:

> **Using a Custom (project-local) Version of npm**
if npmVersion is specified, the plugin installs that version of npm into npmWorkDir by the npmSetup task and use it.
If npmVersion is not specified and a locally-installed npm exists, the plugin will use it.
Otherwise, the plugin will use the npm bundled with the version of node installation.

So, what is meant by "... a locally-installed npm exists"? 

- Project-local?  How would it get there in the first place if I didn't specify an npmVersion?
- Globally-installed npm?  That is: on the machine, not downloaded by the plugin ( and _not_ what I want)?   
- Bundled version? Then what's the point of the last sentence?

**Comment by web-devel** [comment]
https://github.com/srs/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/npm/NpmExecRunner.groovy#L43

**Comment by mconner** [comment]
@web-devel  Wouldn't you need npm to be set up in the first place so that the node_modules can be populated?  

Anyway:
When I first posted this question, back in November, _I thought_ I had tested download without specifying an npmVersion (as you suggest), and _I thought_ it didn't work.  I just tried it again (created an NpmTask that gets the version).  And, ... yeah, it sure looks like its working exactly as I want.  The version reported is the bundled version, and not my global version (nor the one I had originally specified, for that matter).  Also, no npmWorkingDir was created.  

Thanks!

So for the record this works just fine:
```
node {
    // Download, rather than use any globally installed version.
    download = true
    // Version of node to download.
    version = '8.9.1'
    // not setting npmVersion

   // other, unrelated, options:
   ...
}
```
