### ISSUE TITLE
Fix Gradle 6.0 Deprecations

### ISSUE THREAD

**Issue by cdietrich** [srs/gradle-node-plugin#316]
When running with Gradle 5.0 i am getting following deprecation warning

```
> Task :nodeSetup
The IvyArtifactRepository.layout(String, Closure) method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the IvyArtifactRepository.patternLayout(Action) method instead.
```

**Comment by cdietrich** [comment]
@deepy am not sure if the can and should be done right know.
patternLayout is still incubating api

**Comment by deepy** [comment]
I'm strangely enough not getting this warning on https://github.com/node-gradle/gradle-node-plugin, not even with `--warning-mode all`

**Comment by cdietrich** [comment]
are you sure you execute nodeSetup actually?

**Comment by cdietrich** [comment]
https://github.com/cdietrich/gradle-node-plugin-issue316

**Comment by deepy** [comment]
I'm not getting this in my local test repo, which apart from using the old plugin syntax is seemingly identical, strange.
Your test-case works brilliantly though!

**Comment by cdietrich** [comment]
switched to node-gradle/gradle-node-plugin which has my fix
