### ISSUE TITLE
1.3.0 version is not accessible

### ISSUE THREAD

**Issue by vitalyster** [srs/gradle-node-plugin#326]
`https://plugins.gradle.org/m2/com/moowork/gradle/gradle-node-plugin/1.3.0/gradle-node-plugin-1.3.0.pom` show error

**Comment by vitalyster** [comment]
Got 1.3.1

**Comment by srs** [comment]
1.3.1 is working for you?

**Comment by vitalyster** [comment]
Yes, I'm not using Gulp plugin
