### ISSUE TITLE
npm setup should set PATH to point to version of node

### ISSUE THREAD

**Issue by time4tea** [srs/gradle-node-plugin#34]
gradle-node-plugin v0.7

On a system without any version of node installed in the path, and specifying npmVersion, npmSetup will fail for some modules. It seems that these modules require running node, which isn't in the path.
You will need to remove node_modules if you switch between specifying the npmVersion and not..

Here is a minimal example:

package.json
{
  "name": "example",
  "description": "ex",
  "author": "time4tea",
  "dependencies": {
    "safefs": "3.1.1"
  }
}

build.gradle
apply plugin: 'node'

task wrapper(type: Wrapper) {
    gradleVersion = '2.1'
}

node {
    version = "0.10.33"
    npmVersion = "2.1.6"
    download = true
}

buildscript {
    repositories {
        jcenter()
	mavenCentral()
    }
    dependencies {
        classpath group: 'com.moowork.gradle', name: 'gradle-node-plugin', version:'0.7'
    }
}

group = "net.time4tea.example"

npmInstall {
    def bob = [:]
    bob << System.getenv();
    bob["PATH"] = bob["HOME"] + "/.gradle/nodejs/node-v0.10.33-linux-x64/bin:" + System.getenv('PATH')
    // uncomment the next line to make me work...
    //environment bob
}

Running the examples:

# without path hack
rm -rf node_modules && ./gradlew npmInstall
:nodeSetup UP-TO-DATE
:npmSetup SKIPPED
:npmInstall
npm WARN package.json example@ No repository field.
npm WARN package.json example@ No README data

> safefs@3.1.1 preinstall /home/jrichardson/work/test/node_modules/safefs
> node ./cyclic.js

sh: 1: node: not found

# with path hack
:nodeSetup UP-TO-DATE
:npmSetup SKIPPED
:npmInstall
npm WARN package.json example@ No repository field.
npm WARN package.json example@ No README data

> safefs@3.1.1 preinstall /home/jrichardson/work/test/node_modules/safefs
> node ./cyclic.js

safefs@3.1.1 node_modules/safefs
└── graceful-fs@2.0.3

BUILD SUCCESSFUL

**Comment by kyyash** [comment]
How to use this option ? 

We are using this plugin but however, we want to set PATH system property before we run the npm commands using this plugin
