### ISSUE TITLE
Cannot download node version

### ISSUE THREAD

**Issue by hukadev** [srs/gradle-node-plugin#360]
Hello,

I ran a gradle build then got this error:
> Could not find org.nodejs:node:13.3.0.
     Searched in the following locations:
       - https://nodejs.org/dist/v13.3.0/ivy.xml
     Required by:
         project X

I try to access this link: https://nodejs.org/dist/v13.3.0/
Then I realized that there is no ivy.xml file.

Does anybody find the way to fix it?

Best regards,
Huka

**Comment by deepy** [comment]
See https://github.com/srs/gradle-node-plugin/issues/292#issuecomment-562828714

This is the same issue as #292

**Comment by hukadev** [comment]
Hi @deepy 

Thanks for you help.

Regards,
Huka
