### ISSUE TITLE
npm WARN deprecated request

### ISSUE THREAD

**Issue by cdalexndr** [srs/gradle-node-plugin#366]
When I run a **NpmTask** it prints this warning:
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

Gradle task:
```
task npm_install_dep(type: NpmTask) {
    workingDir = file("$buildDir/public")
    args = ["install", '--production']
}
```

**Comment by deepy** [comment]
This is npm telling you that you're using a deprecated package, not an issue with the plugin

**Comment by cdalexndr** [comment]
ok, thanks
