### ISSUE TITLE
Support for limit on parallel task runs

### ISSUE THREAD

**Issue by iamrakesh** [srs/gradle-node-plugin#381]
We use this plugin (an older version) to execute npm scripts in our builds and with Gradle parallel run enabled. npm script we execute spawn multiple node.exe processes resulting very high CPU usage, which in turn slows down task execution.

Would it be possible to have limit on parallel NpmTask runs ?

**Comment by deepy** [comment]
Maybe a [shared build service](https://docs.gradle.org/current/userguide/build_services.html#concurrent_access_to_the_service) with limits on concurrent access could work?

But this repository is as far as I know abandoned, see https://github.com/srs/gradle-node-plugin/issues/315 for the history and the maintained fork

**Comment by iamrakesh** [comment]
@deepy
I'll try shared build service approach.
This repo is indeed abandoned and I missed to check that.
Thank you (y)
