### ISSUE TITLE
Clarify documentation intro on default behavior

### ISSUE THREAD

**Issue by segfly** [srs/gradle-node-plugin#40]
I spent 30 minutes trying to figure out why this plugin would not download node. The nodeSetup task was always being skipped. I had to add the node{download=true} to my buildscript.

The root "issue" was for me, was the documentation in the first paragraph made it sound like download=true was the default behavior. I had to dig through the code as to why and find that download=false is the default.

I suggest that the documentation clarify this, or (possibly better) the default is changed to true.

Thanks.

**Comment by srs** [comment]
Yes, I am actually thinking that download should be true by default and maybe the property should be named "useLocalNode" or something similar. Will try to fix up the docs. Thanks for the input.

**Comment by srs** [comment]
Have added a note in the documentation. Also, this will change in the future with a new flag called `useGlobalNode` which will be default to `false`. The `download` flag will then be deprecated.
