### ISSUE TITLE
SetupTask's "ext" property causes naming conflicts

### ISSUE THREAD

**Issue by stevesaliman** [srs/gradle-node-plugin#41]
The ```SetupTask``` currently has a property named ```ext``` of type ```NodeExtension```.  The name ```ext``` is probably a bad idea since Gradle developers will expect ```ext``` to be an ```ExtraPropertiesExtension``` based on http://www.gradle.org/docs/current/dsl/org.gradle.api.plugins.ExtraPropertiesExtension.html. 

Even worse, the standard way of adding a property (or method) to a task is with a statement like ```task.ext.myProperty = 'myValue'```, but if a developer of plugin tries to do this, they will get a NullPointerException because ```ext``` starts out null.

**Comment by srs** [comment]
Thanks for noticing this. Will fix this by using another variable name.

**Comment by srs** [comment]
Issue fixed.
