### ISSUE TITLE
64-bit versions of windows use 32-bit node.exe

### ISSUE THREAD

**Issue by ekaufman** [srs/gradle-node-plugin#47]
The exeDependency for Windows always pulls in the 32-bit node.exe even when running a 64-bit version of windows. 

I created PR https://github.com/srs/gradle-node-plugin/pull/46 which will pull in the 64-bit version of node.exe when running 64-bit versions of Windows.

The specific nuisance this issue causes if you use node-sass, the node-sass installer looks at the process architecture to determine which libsass binding to install, and if I've already installed node-sass manually through an 'npm install' that will have installed the 64-bit binding in node_modules, and that will generate errors when gradle-node-plugin tries to run it with node.exe*32.

**Comment by srs** [comment]
Thanks. Closing this since the PR's pulled.
