### ISSUE TITLE
Node tasks should honour workDir property

### ISSUE THREAD

**Issue by Antillean** [srs/gradle-node-plugin#48]
Setting the workDir property on the node object doesn't also set the workingDir property on the default node tasks (such as npmInstall). This results in npm looking for my package.json in the directory of the project I'm running from rather than in my working directory. I've had to work around it by making a task npmInstallCustom as follows:

```javascript
task npmInstallCustom(type: NpmTask) {
    execOverrides {
        it.workingDir = nodeBuildDir
    }

    setArgs( ['install'] )

    inputs.file { file("$nodeBuildDir/package.json") }
    outputs.dir { file("$nodeBuildDir/node_modules") }
}
```

Additionally the inputs file defined for the NpmInstallTask is a (possibly non-exstient) package.json in the project directory. Line 18 of NpmInstallTask.groovy reads:

```java
getInputs().file( new File( this.project.getProjectDir(), 'package.json' ) )
```

It'd be good if the NpmInstallTask (and perhaps all NodeTasks or all NpmTasks?) defaulted its/their exec working directory and inputs directory to the working directory set on the node object. 

(I've raised [a similar issue with the grunt plugin](https://github.com/srs/gradle-grunt-plugin/issues/22).)

**Comment by srs** [comment]
Thanks for the tip. Will look into this (in both projects).

**Comment by nmalaguti** [comment]
I've submitted a PR that should address this https://github.com/srs/gradle-node-plugin/pull/52

**Comment by srs** [comment]
This is now merged into master. Closing this issue.
