### ISSUE TITLE
No such property: nodeModulesDir / unchangeable gulp/grunt-plugin path afterwards

### ISSUE THREAD

**Issue by acromcia** [srs/gradle-node-plugin#53]
Hey. I copied ```node extension  block settings``` and ```gradle.build``` fails with error:
```
No such property: nodeModulesDir for class: com.moowork.gradle.node.NodeExtension_Decorated
```
Right after: 
```java
node {
    ...
    nodeModulesDir = file("${project.projectDir}/../something")
}
```
While ```workDir``` works fine

```java
    workDir = file("${project.buildDir}/nodejs")
```

Edit: 

I noticed that it seems to work in the ```0.10-SNAPSHOT``` but I stumbled upon another issue. 
When I change ```nodeModulesDir``` directory path, ```gradle-gulp/grunt plugins``` will fail because of ```gulp/grunt``` paths in ```src/main/groovy/com/moowork/gradle/gulp/GulpTask.groovy```
```
private final static String GULP_SCRIPT = 'node_modules/gulp/bin/gulp.js';
...
def localGulp = this.project.file( GULP_SCRIPT )
```

Cheers

**Comment by scholarsmate** [comment]
Could really use this to help configure an out-of-tree build.  Do you plan on releasing soon?

**Comment by kevgliss** [comment]
Yes, a release would be good. Has this project been abandoned?

**Comment by srs** [comment]
No, not abandoned. Just lack of time :-( But will release a new version very soon. I will also merge node, grunt and gulp modules as one since all of them has some similar code.

**Comment by kevgliss** [comment]
Awesome! I thanks for all the hard work... I know life gets in the way. :-)

**Comment by srs** [comment]
Closing this one. Reopen if I made a mistake :-)
