### ISSUE TITLE
Support io.js

### ISSUE THREAD

**Issue by rocketraman** [srs/gradle-node-plugin#54]
It would be great if the plugin could support [IO.js](https://iojs.org/en/index.html) as well as NodeJS.

**Comment by srs** [comment]
Will look at this. Have not tested IO.js yet, but it looks interesting.

**Comment by rocketraman** [comment]
Maybe this is irrelevant now. It looks like io.js is rejoining the Node Foundation and converging with NodeJS: https://medium.com/node-js-javascript/io-js-week-of-may-15th-9ada45bd8a28

**Comment by srs** [comment]
Closing this since NodeJS and IO.js will merge.
