### ISSUE TITLE
How can I change the location of package.json?

### ISSUE THREAD

**Issue by verystrongjoe** [srs/gradle-node-plugin#55]
Normally, the location of it is the root of project directory. But I moved the file to the grunt folder.

How can I change it?

**Comment by dougborg** [comment]
I assume you are trying to configure the `npmInstall` task to run in a `grunt` subdirectory. If that is the case try:

```groovy
npmInstall {
  execOverrides {
    it.workingDir = file('grunt')
  }
}
```

If something like that doesn't work or you mean something else, let me know and try to give a more specific example of the problem you are trying to solve.

**Comment by verystrongjoe** [comment]
@dougborg  Thanks. Your answer is exactly the one I want. But I already set the package.json file to the root directory of all my projects. I will try it next times. Thanks.!!!
