### ISSUE TITLE
Plugin on Windows attempts to download Linux version 

### ISSUE THREAD

**Issue by sruffing** [srs/gradle-node-plugin#60]
The VariantBuilder will attempt to call 
```
getTarGzDependency( 'linux', 'x86' )
```
if the variant is for Windows.

I think when the refactoring was done in https://github.com/srs/gradle-node-plugin/commit/590fab4f5b12c65032ffae8111f693adc8121ece that the code should have been

```
if ( !variant.windows) {
```

or reverse the code inside the conditionals around. Even the unit test in VariantBuilderTest seems to be wrong. There is no way you should grab the linux build if the property is Windows!

**Comment by srs** [comment]
Actually it's fetching the linux tar.gz dependency only for NPM and other node resources. The EXE (node.exe) is still windows. I should probably have written a comment about this since it sounds wierd, but it actually works. Does it not work for you?

**Comment by sruffing** [comment]
I am running on a Windows 7 Enterprise box, and it attempts to pull the Linux version
```
Could not resolve all dependencies for configuration ':nodeDist'.
> Could not find org.nodejs:node:0.10.38.
  Searched in the following locations:
http://{artifactory}/artifactory/{repo}/org/nodejs/node/v0.10.38/ivy.xml
http://{artifactory}/artifactory/{repo}/org/nodejs/node/v0.10.38/node-v0.10.38-linux-x86.tar.gz
```

We have it configured as...
```
node {
    version = '0.10.38'
    distBaseUrl = 'http://{artifactory}/artifactory/{repo}/org/nodejs/node'
    download = true
    workDir = file("${buildDir}/nodejs")
}
```

**Comment by srs** [comment]
Right, if you try to comment out the "distBaseUrl" option and try again, does it work? It actually needs the resources inside the linux version for things to work. It also needs the node.exe. Since node does not distribute an official (zip or tar) archive for windows I need to rely on the linux version. 

So, to get this to work with your setup, you will have to publish the linux archive to your artifactory repo.

**Comment by sruffing** [comment]
Ok, I'm following now better. Thanks for the clarification. It does work without providing the distBaseUrl.

I think I tracked it down to an x86 versus our repository having an x64 instance only. So for Windows you only pull the 32-bit tar dependency, but still use the 64-bit Windows compiled version. I can see how that confused us when importing some of the libraries!

Thanks for the help.

**Comment by srs** [comment]
Yes, it can be confusing. I see that now and will try to write a FAQ when I get the time to do it. 

I am glad that that it worked out ok. Happy to answer any questions :-)
