### ISSUE TITLE
NodeTask.setEnvironment() does not work properly in download=true mode

### ISSUE THREAD

**Issue by blop** [srs/gradle-node-plugin#62]
Hello,

Since those changes :
https://github.com/srs/gradle-node-plugin/commit/8b4b26b4eedae3534f7b34ce66d9caa2b1c0ba86

The this.environment variable is automatically set when using download=true.
This prevents the configuration of a custom environment.

NodeExecRunner should merge any configured environment and only ensure it's nodeBinDirPath is included in the PATH without overriding it completely.

Maybe something like this :
```
            def nodeBinDirPath = this.variant.nodeBinDir.getAbsolutePath()

            def nodeEnvironment = this.environment
            if (nodeEnvironment == null) {
                 nodeEnvironment = [:]
                 nodeEnvironment << System.getenv()
            }

            // Take care of Windows environments that may contain "Path" OR "PATH" - both existing
            // possibly (but not in parallel as of now)
            if (nodeEnvironment['Path'] != null) {
                nodeEnvironment['Path'] = nodeBinDirPath + File.pathSeparator + nodeEnvironment['Path']
            } else {
                nodeEnvironment['PATH'] = nodeBinDirPath + File.pathSeparator + nodeEnvironment['PATH']
            }
            this.environment = nodeEnvironment
```

Thank you.

Olivier

**Comment by srs** [comment]
Thanks. Will look at how we could do this better.

**Comment by srs** [comment]
This is now hopefully fixed in https://github.com/srs/gradle-node-plugin/commit/4c57e0c7bb1f6fcc89a8daa5ac0c23b3d032f886.

**Comment by srs** [comment]
Added some tests for this too so I am certain it's fixed. Closing this.
