### ISSUE TITLE
Bad resolution of 64 bit nodejs dependency

### ISSUE THREAD

**Issue by sandipchitale** [srs/gradle-node-plugin#65]
For me:

DefaultExternalModuleDependency{group='org.nodejs', name='x64/node', version='0.10.38', configuration='default'}

resolves to a bogus, 32 bit node.js. It appears to be coming from 

http://snapshots.repository.codehaus.org/org/nodejs/x64/node/0.10.38/x64

It may be bad Artifactory set up - because the above does not even resolve anymore.

My question is what is the right repository to get dependency from?

**Comment by sandipchitale** [comment]
I worked around it by downloading the right version in

```
flatDirRepository/
  x64/
    node.exe
```
and then defining:

```
repositories {
	flatDir {
		dirs 'flatDirRepository'
	}
	...
}
```

But documentation proper way to solve it will be helpful.

Also not sure why ```distBaseUrl ``` is not really used to get node distribution, but instead a dependency resolution is used. It may be that I am not understanding the code properly.

**Comment by srs** [comment]
Right now it will try every repository in the repositories list until it finds the right one. It's not a very good way to do it, but it has worked so long (except in your case it seems). The right repository is an ivy-repository with some custom patterns that will try to match using  gradle dependency.

**Comment by sandipchitale** [comment]
Can you please explain:

**Comment by srs** [comment]
The plugin (gradle-node-plugin) adds a ivy repository to the node distribution root. It's using an ivy repo just becouse it's the only one that can handle this type of requests. It would be better to create a specialized repository for getting the node exec but right now we just use an ivy repo. 

This repo is added as the last one so every other repos you are adding in ``repositories`` clause will be resolved before this one. If (for some reason) it finds a file on the path it will get that file and DO NOT move to the next one. 

In the latest SNAPSHOT of gradle-node-plugin I have done it a littlebit different so you will probably not have the same problem that you encounter now.

**Comment by sandipchitale** [comment]
Aha...that explains it. Actually in the end it turned out that our Artifactory cache had a corrupt node-*.exe file (only 73 bytes)  for 64 bit variant which apparently originally came from the 

http://snapshots.repository.codehaus.org/org/nodejs/x64/node/0.10.38/x64

I had not even expected this.

After cleaning that up it ended up getting to the ivy repo that you add and it worked.

I appreciate your responses.
