### ISSUE TITLE
nodejs v4.0.0 automatic install fails on windows

### ISSUE THREAD

**Issue by chpro** [srs/gradle-node-plugin#66]
One windows the auto installation does not work because path for binaries have changed in https://nodejs.org/dist/v4.0.0/ it is `win-x64` or `win-x86` for older versions it was only `x64` or root folder.

**Comment by SebaSOFT** [comment]
+1

**Comment by srs** [comment]
I saw that. Will fix this so it will work for 4.x.

**Comment by mjdetullio** [comment]
Politely asking for a release to get this fix out there :)

**Comment by srs** [comment]
Your request is granted :-) Will create a release in a couple of days.

**Comment by srs** [comment]
Closing this issue since the code is in master. Will release tomorrow.
