### ISSUE TITLE
NodeExtension.groovy bad url

### ISSUE THREAD

**Issue by AvihayTsayeg** [srs/gradle-node-plugin#67]
http://nodejs.org/dist/ is no longer supported 
use
https://nodejs.org/dist/ (ssl)

see pull request #69

**Comment by ftorghele** [comment]
+1

**Comment by makuk66** [comment]
+1

**Comment by talsalmona** [comment]
+1

**Comment by ftorghele** [comment]
http://nodejs.org/dist/ is working again

**Comment by AvihayTsayeg** [comment]
Thx,
I will close the PR

**Comment by srs** [comment]
Which is the right one, https or http? Should we prefer https over http?

**Comment by AvihayTsayeg** [comment]
you should use https by default
see:
https://github.com/nodejs/node ``` Releases are available at https://nodejs.org/dist/  ```
https://github.com/eirslett/frontend-maven-plugin/pull/270 ``` NodeJS sometimes doesn't permit http requests, which can cause build failures.```

**Comment by srs** [comment]
Ok. Then I will fix it.

**Comment by fiskr** [comment]
@srs, I have already fixed it; see see request #69
It just needs to be merged.

**Comment by srs** [comment]
The branch seems to be deleted. Could you add a pull request? Thanks.

**Comment by fiskr** [comment]
Sorry - my bad, I was thinking this was for the [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) project. I haven't made a pull request for gradle-node-plugin.

I think AvihayTsayeg's pull request #69 would be what you need.

**Comment by srs** [comment]
@AvihayTsayeg, could you please add the pull request again? Looked at it and it seems to be closed by you. Thanks.

**Comment by AvihayTsayeg** [comment]
@srs 
It is reopen and rebased #69.
Regards

**Comment by srs** [comment]
Merged. Closing this issue.
