### ISSUE TITLE
Merging node, gulp and grunt plugins

### ISSUE THREAD

**Issue by srs** [srs/gradle-node-plugin#71]
Hi.

I am thinking of merging the codebase for node, gulp and grunt plugins into a new project called "gradle-node". Both the gulp and grunt plugins are very dependant on the node plugin so in my view it makes sense. Also, it takes some time to maintain 3 different projects instead of one.

It will still be able to just use one of the plugins, but it's bundled as one jar (not 3). 

Any toughts about this?

BR,
Sten Roger

**Comment by fritzrichter** [comment]
I like the idea of having just one plugin! +1

**Comment by twwwt** [comment]
+1

**Comment by lex-em** [comment]
Hi, srs. Can you add brunch support for new plugin?

**Comment by dvaske** [comment]
+1

**Comment by srs** [comment]
Good that nobody has any objections. I will check in the initial merge very soon (in it's own branch). Also, I have plans to include other Node-tech like Bower and Brunch.

**Comment by srs** [comment]
The merge will be done right after the next release and I will mark the new versions for 1.0.

**Comment by srs** [comment]
Will move the merge for 1.0 version. Probably right after 0.13.

**Comment by adrian-clemente** [comment]
+1

**Comment by srs** [comment]
Done.
