### ISSUE TITLE
Plugin fails to download node (version > 4.0) in windows environment

### ISSUE THREAD

**Issue by nibin** [srs/gradle-node-plugin#75]
The following gradle snippet fails to run in windows.

```
apply plugin: 'base'
apply plugin: 'com.moowork.node'
apply plugin: 'com.moowork.grunt'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath "com.moowork.gradle:gradle-node-plugin:0.10"
        classpath "com.moowork.gradle:gradle-grunt-plugin:0.10"
        classpath "commons-codec:commons-codec:1.9"
    }
}

node {
	// Version of node to use.
	version = '4.1.0'

	// Version of npm to use.
	npmVersion = '2.14.3'

	// Base URL for fetching node distributions (change if you have a mirror).
	distBaseUrl = 'http://nodejs.org/dist'

	// If true, it will download node using above parameters.
	// If false, it will try to use globally installed node.
	download = true

	// Set the work directory for unpacking node
	workDir = file("${project.buildDir}/nodejs")

	// Set the work directory where node_modules should be located
	nodeModulesDir = file("${project.projectDir}")
}

grunt {
    // Set the directory where Gruntfile.js should be found
    workDir = file("${project.projectDir}")

    // Whether colors should output on the terminal
    colors = true

    // Whether output from Grunt should be buffered - useful when running tasks in parallel
    bufferOutput = false
}
```
-----------

It gives the below error:
```
>gradlew --info war

--snip--
All projects evaluated.
Selected primary task 'war' from project :
Resource missing. [HTTP GET: http://nodejs.org/dist/v4.1.0/ivy.xml]
Resource missing. [HTTP HEAD: http://nodejs.org/dist/v4.1.0/x64/node.exe]

FAILURE: Build failed with an exception.

* What went wrong:

Could not resolve all dependencies for configuration ':ui:nodeDist'.
> Could not find org.nodejs:x64/node:4.1.0.
  Searched in the following locations:
      http://nodejs.org/dist/v4.1.0/ivy.xml
      http://nodejs.org/dist/v4.1.0/x64/node.exe
  Required by:
      spartan:ui:unspecified

* Try:

Run with --stacktrace option to get the stack trace. Run with --debug option to
get more log output
BUILD FAILED
```

Upon inspection, I found that node versions > 4 is not publishing .exe files. They have .msi files in nodejs downloads.

https://nodejs.org/dist/v4.1.1/

**Comment by jashatton** [comment]
I am getting this on our continous build server as well.  Anybody have a work around?

**Comment by srs** [comment]
Try version 0.11. Node < 4.0.0 is not working with version 0.10 and below.

**Comment by jashatton** [comment]
My apologies, I should have stated version information.  I am not sure what was happening but, after retrying today with Node 0.12.4 and the plugin version of 0.10, I have it working without any issues.  Thanks for putting this plugin out for others to use.

**Comment by srs** [comment]
What I mean is to try with Gradle Node Plugin version 0.11 (the latest). This will work with Node 4.x and above.

**Comment by jashatton** [comment]
I wasn't planning on a upgrade just yet, so the 0.12.4 using 0.10 works for me for now.  Thanks

**Comment by srs** [comment]
Ok. But, in case you want to use Node 4.x and above, you will have to upgrade to gradle-node-plugin 0.11 :-)

**Comment by Darkvater** [comment]
I have the same problem here. Using gradle-node-plugin 0.11 and running the number task always complains about the ivy file missing from nodejs.org. Both 4.1.0 and 0.12.4 are failing even with the snippet from the original poster.

**Comment by srs** [comment]
The ivy.xml is tried since it's actually using an Ivy repository in the code, but it should not fail. Could you paste in the error you get. It should not be identical as original poster's error since the URL should probably be different.
