### ISSUE TITLE
Downloading latest Node Version

### ISSUE THREAD

**Issue by alwick** [srs/gradle-node-plugin#89]
I am not sure how to download the latest 4.2.2 version of NodeJS using this plugin:

I tried this:
```javascript
node {
  download = true
  version = '4.2.2'
  npmVersion = '2.14.7'
}
```

I get this:
Could not resolve all dependencies for configuration ':nodeDist'.
> Could not find org.nodejs:x64/node:4.2.2.

Is there a way to do this with the current plugin?  I have spent a lot of time online looking for a solution and haven't found anything...

**Comment by srs** [comment]
Will check later today.
ons. 2. des. 2015 kl. 06.00 skrev Allan Wick <notifications@github.com>:

**Comment by srs** [comment]
Windows or linux/mac?
ons. 2. des. 2015 kl. 15.58 skrev Sten Roger Sandvik <srs@enonic.com>:

**Comment by alwick** [comment]
This is on Windows and using 0.11

**Comment by alwick** [comment]
Any Update on this issue?

**Comment by srs** [comment]
Sorry, it was closed by you so I did not do anything with it since I tought it was fixed. Could you run the same thing with ``--info`` switch and give me the output where it should the actual URL it's trying to download (when it fails)?

**Comment by alwick** [comment]
Resource missing. [HTTP GET: http://nodejs.org/dist/v4.2.2/node.pom]

**Comment by srs** [comment]
That's strange. This was fixed in 0.11, but it seems that it's wrong in your case. I am in the process of changing the resolution process so maybe it will be better after that. Will certainly add more tests around this.

**Comment by alwick** [comment]
I noticed that the osArch variable is set to 'amd64' it may be part of the problem...

**Comment by srs** [comment]
Yes, but still it should actually detect it as 64 bits. Will add ``amd64`` as one of the test criterias.

**Comment by alwick** [comment]
Ok, I found a dependency in another gradle file was setting the plugin version to 0.10.  Updating it fixed my issue.  Sorry for any confusion...
