### ISSUE TITLE
variable access to node executable path

### ISSUE THREAD

**Issue by dsvensson** [srs/gradle-node-plugin#92]
I'm trying to use this plugin in conjunction with 'typescript-gradle-plugin' by adding typescript to package.json as a dependency. As this plugin looks for a global tsc compiler, I need to change its compiler path setting (compilerExecutable). This would be (mocking the existence of $NODE) "$NODE node_modules/typescript/lib/tsc.js" and as node is located in "~/.gradle/nodejs/node-v5.3.0-linux-x64/bin/node" on my setup under Linux I would like to access it via a variable to avoid ugly and platform specific hardcoding. I can't seem to find any way of accessing the node path though. Am I missing something?

https://github.com/sothmann/typescript-gradle-plugin

**Comment by srs** [comment]
If you use the node task instead it will use the right node executable. So, to execute tsc in this way you could do the following:

    task tsc(type: NodeTask) {
       script = file('node_modules/typescript/lib/tsc.js')
       args = [...]
    }

I have not looked at the typescript plugin so I do not know how this does it. But the example above works in one of my own setups.

**Comment by srs** [comment]
Closing this issue since it as a work-around.
