### ISSUE TITLE
Question: npmSetup task looking in wrong folder

### ISSUE THREAD

**Issue by gajo4256** [srs/gradle-node-plugin#98]
Hi,

when I call `nodeSetup` the task will download node-vxxx-linux-x64 and node-vxxx-windows-x64 node versions. If I then run `npmSetup` I will get the following error:

> 16:29:05.480 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
> 16:29:05.711 [ERROR] [system.err] module.js:338
> 16:29:05.712 [ERROR] [system.err]     throw err;
> 16:29:05.712 [ERROR] [system.err]           ^
> 16:29:05.713 [ERROR] [system.err] Error: Cannot find module 'C:\Users\tom\.gradle\nodejs\node-v0.12.2-linux-x86\lib\node_modules\npm\bin\npm-cli.js'
> 16:29:05.714 [ERROR] [system.err]     at Function.Module._resolveFilename (module.js:336:15)
> 16:29:05.714 [ERROR] [system.err]     at Function.Module._load (module.js:278:25)
> 16:29:05.715 [ERROR] [system.err]     at Function.Module.runMain (module.js:501:10)
> 16:29:05.715 [ERROR] [system.err]     at startup (node.js:129:16)
> 16:29:05.716 [ERROR] [system.err]     at node.js:814:3
> 16:29:05.720 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
> 16:29:05.721 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'cmd'' finished with exit value 1 (state: FAILED)
> 

It seems it is looking in the wrong (non-existing) folder (node-vxxx-linux-x86). The thing is sometimes in the past I had that OS version too, but now it won't download it anymore. What am I not seeing (or doing wrong?)

OS: Windows 7, gitBash: 1.9.5 

Many thnx,
Tommy

**Comment by srs** [comment]
Hi. What's the gradle and plugin version?
man. 14. mar. 2016 kl. 16.43 skrev Tomislav Gajsak <notifications@github.com

**Comment by gajo4256** [comment]
Hi,

sorry, forgot to mention it in the first comment.

> plugins {
  id "com.moowork.grunt" version "0.11"
}

**Comment by srs** [comment]
Could you try the new 0.12 version to see if you are experiencing the same?

**Comment by gajo4256** [comment]
Hi,

okay, it seems that from version 0.12 we need both plugins, right?

> plugins {
  id "com.moowork.node" version "0.12"
  id "com.moowork.grunt" version "0.12"
}

I also removed `node` closure with nodeVersion and npmVersion.
And now it seems to work, 2 questions though:
1.) where is node now downloaded
2.) is it good practice to explicitly set the versions for node and npm

Many thnx.
Btw, there should be nicer message when user forgets to include node plugin, this is what it is currently in the log:

> 15:59:43.040 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'gradle-grunt-plugin.jar (com.moowork.gradle:gradle-grunt-plugin:0.12)' in resolver cache: C:\Users\tgajsak\.gradle\caches\modules-2\files-2.1\com.moowork.gradle\gradle-grunt-plugin\0.12\6bbd09e6114662454ea2846dbc5dc8e97dc977d7\gradle-grunt-plugin-0.12.jar
15:59:43.046 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.052 secs
15:59:43.054 [ERROR] [org.gradle.BuildExceptionReporter]
15:59:43.054 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:59:43.055 [ERROR] [org.gradle.BuildExceptionReporter]
15:59:43.055 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:59:43.055 [ERROR] [org.gradle.BuildExceptionReporter] com/moowork/gradle/node/NodePlugin
15:59:43.055 [ERROR] [org.gradle.BuildExceptionReporter] > com.moowork.gradle.node.NodePlugin
15:59:43.056 [ERROR] [org.gradle.BuildExceptionReporter]
15:59:43.056 [ERROR] [org.gradle.BuildExceptionReporter] * Try:

**Comment by gajo4256** [comment]
Okay, I've managed to get it right. New node version(s) are saved in .gradle folder where build.gradle file is.
